name: Cloudflare Pages Deploy

on:
  push:
    branches:
      - {{ .DeployBranch }}

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'
          
      - name: Install dependencies
        run: npm ci
        
      - name: Build
        run: npm run build
        
      - name: Deploy to Cloudflare Pages
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          command: pages deploy {{ .BuildFolder }} --project-name={{ .ProjectName }} --commit-hash=${{ github.sha }}
          
      - name: Send notification
        if: always()
        uses: ./.github/workflows/telegram-notification
        with:
          status: ${{ job.status }}
          project_name: ${{ .ProjectName }}
          project_url: ${{ .ProjectURL }} 