on:
  workflow_call:
    inputs:
      main_job_name:
        required: true
        type: string
      results:
        required: true
        type: string
      service_name:
        required: true
        type: string

jobs:
  telegram_message:
    runs-on: self-hosted
    if: always()
    steps:
      - name: send telegram message on push
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_CHAT_ID }}
          token: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          message: |
            *${{ github.actor }}* created commit:
            Project: ${{ inputs.service_name }}
            Commit message: ${{ github.event.commits[0].message }}
            Build Result: ${{ inputs.results }}
            Repository: ${{ github.repository }}
            Link: https://github.com/${{ github.repository }}/commit/${{github.sha}}
